### PR TITLE
bug: fix integer to string conversion

### PR DESCRIPTION
**Pull request by code-sleuth**
fixes [#35](https://github.com/FusionAuth/go-client/issues/35)

### CODE REVIEW

**Comment by MCBrandenburg** [comment]
Background for why this change is great: https://golang.org/doc/go1.15#vet

**Comment by robotdan** [comment]
Is this fix safe for all string (ish) inputs? The lines of code you changed are actually built. 

See : https://github.com/FusionAuth/fusionauth-client-builder/blob/66d1cc25c2e72c634967303a640a661df286478f/src/main/client/go.client.ftl#L177

The values we would expect on the URI segment are generally going to be a UUID in string 8-4-4-4-12 form, but in the case of the Event Log and Audit Log it will be an integer of some sort, (int or long). 

So I could merge your fix in there - but it will affect all APIs that use `WithUriSegment`. However, from reading the link that @MCBrandenburg posted, it looks like that would be ok. 

Does that seem sound?

**Comment by robotdan** [comment]
I pushed to change to the client builder, and the resulting client build. 
https://github.com/FusionAuth/fusionauth-client-builder/commit/38ba0e3748980c51d4f45cbe63104b8085a00dc5

See if this fixes it.

**Comment by robotdan** [comment]
Thanks for the contribution @code-sleuth much appreciated.  I'll accept this PR. I had to also make this change to the template file in order for it to be persisted after the next build.

**Pull request merged**
